#!/bin/bash

mkdir -p release

output=pipewire-settings@gaheldev.github.com.shell-extension.zip
rm -r release/${output}

(
cd  pipewire-settings@gaheldev.github.com/
zip ../release/${output} *
)

zip release/${output} LICENSE.md
